#!/usr/bin/env python3
"""Turn one rover calibration bag into a ready-to-run FAST-Calib scene.

    python3 scripts/prepare_scene.py calib_data/rover_scene1

Writes <bag>/frame.png (the image nearest the middle of the bag) and
config/qr_params_rover_<scene>.yaml: config/qr_params_rover.yaml with the intrinsics
taken from THIS bag's camera_info and the bag/image/output paths filled in. Generating
them together is the point -- a frame.png run against intrinsics from another
resolution yields a plausible, wrong extrinsic with no error.

Then:
    ros2 launch fast_calib calib_launch.py params_file:=<printed path>
"""
import argparse
import os
import re
import sys

import cv2
import numpy as np
import rosbag2_py
from rclpy.serialization import deserialize_message
from sensor_msgs.msg import CameraInfo, Image, PointCloud2

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGE_TOPIC = '/camera/zed_node/rgb/color/rect/image'
INFO_TOPIC = IMAGE_TOPIC + '/camera_info'
LIDAR_TOPIC = '/rslidar_points'


def to_bgr(msg: Image) -> np.ndarray:
    channels = {'bgra8': 4, 'rgba8': 4, 'bgr8': 3, 'rgb8': 3, 'mono8': 1}
    if msg.encoding not in channels:
        sys.exit(f'unsupported image encoding {msg.encoding}')
    n = channels[msg.encoding]
    rows = np.frombuffer(msg.data, np.uint8).reshape(msg.height, msg.step)
    img = rows[:, :msg.width * n].reshape(msg.height, msg.width, n)
    conv = {'bgra8': cv2.COLOR_BGRA2BGR, 'rgba8': cv2.COLOR_RGBA2BGR, 'rgb8': cv2.COLOR_RGB2BGR}
    return cv2.cvtColor(img, conv[msg.encoding]) if msg.encoding in conv else img.copy()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('bag', help='bag directory recorded with record_scene.sh')
    ap.add_argument('--base', default=os.path.join(PKG, 'config', 'qr_params_rover.yaml'))
    args = ap.parse_args()
    bag = os.path.abspath(args.bag.rstrip('/'))
    scene = os.path.basename(bag)

    reader = rosbag2_py.SequentialReader()
    reader.open(rosbag2_py.StorageOptions(uri=bag, storage_id=''),
                rosbag2_py.ConverterOptions('cdr', 'cdr'))
    reader.set_filter(rosbag2_py.StorageFilter(topics=[IMAGE_TOPIC, INFO_TOPIC, LIDAR_TOPIC]))
    images, info, n_lidar = [], None, 0
    while reader.has_next():
        topic, data, _ = reader.read_next()
        if topic == IMAGE_TOPIC:
            images.append(data)            # keep raw; decode only the chosen one
        elif topic == INFO_TOPIC and info is None:
            info = deserialize_message(data, CameraInfo)
        elif topic == LIDAR_TOPIC:
            n_lidar += 1
    if not images or info is None or n_lidar == 0:
        sys.exit(f'{bag}: need {IMAGE_TOPIC}, {INFO_TOPIC} and {LIDAR_TOPIC}; got '
                 f'{len(images)} images, {"a" if info else "no"} camera_info, {n_lidar} scans')

    img = to_bgr(deserialize_message(images[len(images) // 2], Image))
    if (img.shape[1], img.shape[0]) != (info.width, info.height):
        sys.exit(f'image {img.shape[1]}x{img.shape[0]} != camera_info {info.width}x{info.height}')
    if any(abs(d) > 1e-9 for d in info.d):
        print(f'WARNING: camera_info has distortion {list(info.d)}; expected zeros for the rect image')
    frame = os.path.join(bag, 'frame.png')
    cv2.imwrite(frame, img)

    k = info.k
    values = {
        'fx': k[0], 'fy': k[4], 'cx': k[2], 'cy': k[5],
        'bag_path': f'"{bag}"', 'image_path': f'"{frame}"',
        'output_path': f'"{os.path.join(PKG, "output_" + scene)}/"',
    }
    text = open(args.base).read()
    for key, val in values.items():
        text, n = re.subn(rf'^(\s+{key}:\s*)\S+', rf'\g<1>{val}', text, count=1, flags=re.M)
        if n != 1:
            sys.exit(f'{args.base}: no "{key}:" line to fill')
    text = (f'# GENERATED by scripts/prepare_scene.py from {bag}\n'
            f'# {info.width}x{info.height}, {len(images)} images, {n_lidar} scans. '
            f'Edit the crop box here, not the intrinsics.\n' + text)
    out = os.path.join(PKG, 'config', f'qr_params_rover_{scene}.yaml')
    open(out, 'w').write(text)

    print(f'{info.width}x{info.height}  fx {k[0]:.4f} fy {k[4]:.4f} cx {k[2]:.4f} cy {k[5]:.4f}')
    print(f'{len(images)} images, {n_lidar} lidar scans; frame -> {frame}')
    print(f'ros2 launch fast_calib calib_launch.py params_file:={out}')


if __name__ == '__main__':
    main()
